### ISSUE TITLE
[Proposta] Adicionar o comando 'descreva'

### ISSUE THREAD

**Issue by DanielTolentino** [brennomachado/descreva-mastodon-bot#1]
O intuito é adicionar o termo 'descreva', um comando alternativo mais direto como uma ação para o bot, similar a comandos usados no telegram.

"bot descreva a imagem"

Uso: "@descreva #descreva [texto]"
O contra deste comando é a redundância da @ e tag.

Faz sentido?

**Comment by brennomachado** [comment]
Oi Daniel! 
Faz sentido sim deixar o uso dessa tag também, acho que apenas eu não deixaria ela na instruções, pois acho que poderia adicionar uma camada mais de dificuldade de entender.

Único porém é quando eu for adicionar suporte a descrição de múltiplas imagens (4 no max)... que faria com uso de tags #1, #2...
Uso: "@descreva #descrição #1 [texto_img_1] #2 [texto_img_2] #3 [texto_img_3]"

Usar a palavra descrição adiciona coerência no uso se lido como "descrição 1, descrição 2". Mas ainda assim é possível adicionar "descreva" no comando para contornar usos errados sem atrito para o usuário.

Agradeço o PR feito sobre, só preciso adicionar uma observação nele... pois há mais parte que muda.

Vlw mesmo! <3
